### ISSUE TITLE
non sense 

### ISSUE THREAD

**Issue by runtimefailure** [QuakedK/0-Delay#1]
```
echo Choose an option:
echo 1. Quaked Ultimate Performance 
echo 2. Quaked Ultimate Performance Idle Off  
echo 3. Skip!
set /p option="Enter option number: "
if "%option%"=="1" (
  echo.
  powercfg -import "C:\Delay Destroyer Tools\Power Plan\Quaked Ultimate Performance.pow"
  timeout 2 > nul
  goto :Activatecpl
) else if "%option%"=="2" (
  echo. 
  powercfg -import "C:\Delay Destroyer Tools\Power Plan\Quaked Ultimate Performance Idle Off.pow"
  timeout 2 > nul
  goto :Activatecpl
) else if "%option%"=="3" (
  echo.
  echo Skipping!
  goto :EndPower
  timeout 1 > nul 
) else (
  cls
  chcp 437 >nul
  powershell -Command "Write-Host 'Invalid choice, Please choose Y or N.' -ForegroundColor White -BackgroundColor Red"
  timeout 2 > nul
  goto :SkipDeviceManager
) 
```

how does this shit work when i dont have it on my pc

**Comment by QuakedK** [comment]
# Power Plan Question.

The pow is located in C:\Delay Destroyer Tools\Power Plan\"Power Plan Name." Meaning yes the pow is in fact located on you're pc under your C drive and get's imported via powercfg -import command.

# Delay Destroyer Tools Folder

The tools folder gets download at the beginning and contains Timer Res, Power Plans and VC Redist.
View the code down below.

:: (Quaked) Downloading Delay Destroyer Tools at Start, Includes Timer Res, Power Plans and VC Redist.
set "fileURL=https://github.com/QuakedK/Downloads/raw/main/DelayDestroyerTools.zip"
set "fileName=Delay Destroyer Tools.zip"
set "extractFolder=C:\Delay Destroyer Tools"
set "downloadsFolder=C:\"
if not exist "%downloadsFolder%\%fileName%" (
    curl -s -L "%fileURL%" -o "%downloadsFolder%\%fileName%"
    timeout 1 > nul
    mkdir "%extractFolder%" > nul
    pushd "%extractFolder%"
    tar -xf "%downloadsFolder%\%fileName%" --strip-components=1
    popd
    del /q "C:\Delay Destroyer Tools.zip" >nul 2>&1
) else (
    echo "%fileName%" already exists in "%downloadsFolder%". >nul 2>&1
)

**Comment by runtimefailure** [comment]
![image](https://github.com/user-attachments/assets/5c2d07f6-e5fb-4861-a42f-2781be1bb9ae)
 fym?
